---
name: cmpsc-101-fall-2018-practical1
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        practicalone/Swap.java:
            --multi 3 --language Java
            --fragment "println(" --count 6 --exact
src/test:
    java:
        practicalone/TestSwap.java:
            --multi 1 --language Java
            --fragment "@Test" --count 3 --exact
# --> check the number of commits beyond a threshold
--commits 10
# --> check that the program executes and produces 20 lines of output
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 6 --exact
--command "gradle -q --console plain run" --fragment "Values before the swap" --count 1 --exact
--command "gradle -q --console plain run" --fragment "Values after the swap" --count 1 --exact
--command "gradle -q --console plain run" --fragment "10" --count 2 --exact
--command "gradle -q --console plain run" --fragment "20" --count 2 --exact
